function uuidgen() {
  if (crypto) {
    return {
      result: crypto.randomUUID(),
      author: "Genereted by randomUUID"
    };
  } else {
    let uuid = "";
    for (let i = 0; i < 8; i++) {
      if (i === 3) {
        uuid += (Math.floor(Math.random() * 0xfff) + 0x4000).toString(16) + "-";
      } else if (i === 4){
        uuid += (Math.floor(Math.random() * 0x3fff) + 0x8000).toString(16) + "-";
      } else {
        uuid += ("0000" + Math.floor(Math.random() * 0xffff).toString(16)).slice(-4);
        if (i === 1 || i === 2){
            uuid += "-";
        }
      }
    }
    return {
      result: uuid,
      author: "Generated by Math.random"
    };
  }
}