function uuidgen() {
  if ("crypto" in window && "randomUUID" in crypto) {
    return {
      result: crypto.randomUUID(),
      author: "Genereted by randomUUID"
    };
  } else {
    let uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(a) {
      let r = (new Date().getTime() + Math.random() * 16)%16 | 0, v = a == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
		});
    return {
      result: uuid,
      author: "Generated by Math.random"
    };
  }
}